In [1]:
import pandas as pd

# Read the CSV file
df = pd.read_csv('/Users/giorgikankia/Documents/GitHub/urbanyxv1/data/geo_general_2020.csv')
df

         longitude   latitude  geo_general_2020
0        40.218194  43.574583          1.316081
1        40.217917  43.574306          1.316081
2        40.218194  43.574306          1.316081
3        40.218472  43.574306          1.316081
4        40.216250  43.574028          1.316081
...            ...        ...               ...
2133696  44.827639  41.000417          0.000000
2133697  45.281528  41.000417          1.735546
2133698  45.289861  41.000417          0.000000
2133699  45.290139  41.000417          0.000000
2133700  45.290417  41.000417          0.000000

[2133701 rows x 3 columns]

In [2]:
# Round the values in the population column to the nearest integer
df['geo_general_2020'] = df['geo_general_2020'].round()

In [3]:
df

         longitude   latitude  geo_general_2020
0        40.218194  43.574583               1.0
1        40.217917  43.574306               1.0
2        40.218194  43.574306               1.0
3        40.218472  43.574306               1.0
4        40.216250  43.574028               1.0
...            ...        ...               ...
2133696  44.827639  41.000417               0.0
2133697  45.281528  41.000417               2.0
2133698  45.289861  41.000417               0.0
2133699  45.290139  41.000417               0.0
2133700  45.290417  41.000417               0.0

[2133701 rows x 3 columns]

In [4]:
# Write the updated data back to the CSV file
df.to_csv('geo_general_2020_updated.csv', index=False)