In [1]:
import osmnx as ox
import geopandas as gpd
import pandas as pd

In [2]:
place = ["Tbilisi, Georgia", 
         "Batumi, Georgia", 
         "Kutaisi, Georgia", 
         "Zugdidi, Georgia", 
         "Gori, Georgia", 
         "Poti, Georgia",
         "Sokhumi, Georgia",
         "Akhaltsikhe, Georgia"
        ]

In [19]:
tags = {"amenity": "bank"}
gdf = ox.features_from_place(place, tags)
gdf

                         amenity  atm       bic              brand  \
element_type osmid
node         5312262226     bank  yes  BAGAGE22  საქართველოს ბანკი
             9679293599     bank  yes  JSCRGE22        კრედო ბანკი
             9991255389     bank  yes  TEBAGE22          ტერაბანკი
             10140092587    bank  yes  TBCBGE22       თიბისი ბანკი
             10910789508    bank  yes  BAGAGE22  საქართველოს ბანკი
...                          ...  ...       ...                ...
way          198720197      bank  yes  MIBGGE22     ProCredit Bank
             234902037      bank  yes  LBRTGE22            ლიბერთი
             234902042      bank  yes  JSCRGE22        კრედო ბანკი
             1073296890     bank  yes  TCZBGE22       ზირაათ ბანკი
             1201009491     bank  yes  TBCBGE22       თიბისი ბანკი

                                 brand:en        brand:ru           brand:tr  \
element_type osmid
node         5312262226   Bank of Georgia     Банк Грузии  Gürcistan Bankası
             9679293599        Credo Bank      Кредо Банк                NaN
             9991255389          Terabank        Терабанк                NaN
             10140092587         TBC Bank     ТиБиСи Банк                NaN
             10910789508  Bank of Georgia     Банк Грузии  Gürcistan Bankası
...                                   ...             ...                ...
way          198720197     ProCredit Bank  ПроКредит Банк                NaN
             234902037            Liberty         Либерти                NaN
             234902042         Credo Bank      Кредо Банк                NaN
             1073296890       Ziraat Bank     Зираат Банк     Ziraat Bankası
             1201009491          TBC Bank     ТиБиСи Банк                NaN

                         brand:wikidata  check_date  \
element_type osmid
node         5312262226        Q2469733  2023-10-14
             9679293599             NaN  2023-04-22
             9991255389             NaN  2022-12-04
             10140092587       Q2620975  2024-03-05
             10910789508       Q2469733         NaN
...                                 ...         ...
way          198720197              NaN         NaN
             234902037         Q6541585         NaN
             234902042              NaN         NaN
             1073296890         Q696003         NaN
             1201009491        Q2620975  2024-02-11

                                         contact:email  ...  \
element_type osmid                                      ...
node         5312262226         customerservice@bog.ge  ...
             9679293599                  info@credo.ge  ...
             9991255389               info@terabank.ge  ...
             10140092587                           NaN  ...
             10910789508        customerservice@bog.ge  ...
...                                                ...  ...
way          198720197    geo.info@procredit-group.com  ...
             234902037                      info@lb.ge  ...
             234902042                   info@credo.ge  ...
             1073296890                            NaN  ...
             1201009491                            NaN  ...

                         payment:american_express payment:apple_pay  \
element_type osmid
node         5312262226                       NaN               NaN
             9679293599                       NaN               NaN
             9991255389                       NaN               NaN
             10140092587                      NaN               NaN
             10910789508                      NaN               NaN
...                                           ...               ...
way          198720197                        NaN               NaN
             234902037                        NaN               NaN
             234902042                        NaN               NaN
             1073296890                       NaN               NaN
             1201009491                       NaN               NaN

                         payment:diners_club payment:discover_card  \
element_type osmid
node         5312262226                  NaN                   NaN
             9679293599                  NaN                   NaN
             9991255389                  NaN                   NaN
             10140092587                 NaN                   NaN
             10910789508                 NaN                   NaN
...                                      ...                   ...
way          198720197                   NaN                   NaN
             234902037                   NaN                   NaN
             234902042                   NaN                   NaN
             1073296890                  NaN                   NaN
             1201009491                  NaN                   NaN

                         payment:google_pay payment:unionpay access  \
element_type osmid
node         5312262226                 NaN              NaN    NaN
             9679293599                 NaN              NaN    NaN
             9991255389                 NaN              NaN    NaN
             10140092587                NaN              NaN    NaN
             10910789508                NaN              NaN    NaN
...                                     ...              ...    ...
way          198720197                  NaN              NaN    NaN
             234902037                  NaN              NaN    NaN
             234902042                  NaN              NaN    NaN
             1073296890                 NaN              NaN    NaN
             1201009491                 NaN              NaN    NaN

                         membership shop                   description:en
element_type osmid
node         5312262226         NaN  NaN                              NaN
             9679293599         NaN  NaN                              NaN
             9991255389         NaN  NaN                              NaN
             10140092587        NaN  NaN                              NaN
             10910789508        NaN  NaN                              NaN
...                             ...  ...                              ...
way          198720197          NaN  NaN  Headquarters and Central Branch
             234902037          NaN  NaN                              NaN
             234902042          NaN  NaN                              NaN
             1073296890         NaN  NaN                              NaN
             1201009491         NaN  NaN                              NaN

[443 rows x 102 columns]

In [20]:
gdf.reset_index([0, 1])
new_gdf = gdf.reset_index(['element_type','osmid'])
new_gdf

,element_type,osmid,amenity,atm,bic,brand,brand:en,brand:ru,brand:tr,brand:wikidata,...,payment:american_express,payment:apple_pay,payment:diners_club,payment:discover_card,payment:google_pay,payment:unionpay,access,membership,shop,description:en
0,node,5312262226,bank,yes,BAGAGE22,საქართველოს ბანკი,Bank of Georgia,Банк Грузии,Gürcistan Bankası,Q2469733,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,node,9679293599,bank,yes,JSCRGE22,კრედო ბანკი,Credo Bank,Кредо Банк,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,node,9991255389,bank,yes,TEBAGE22,ტერაბანკი,Terabank,Терабанк,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,node,10140092587,bank,yes,TBCBGE22,თიბისი ბანკი,TBC Bank,ТиБиСи Банк,NaN,Q2620975,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,node,10910789508,bank,yes,BAGAGE22,საქართველოს ბანკი,Bank of Georgia,Банк Грузии,Gürcistan Bankası,Q2469733,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,way,198720197,bank,yes,MIBGGE22,ProCredit Bank,ProCredit Bank,ПроКредит Банк,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Headquarters and Central Branch
439,way,234902037,bank,yes,LBRTGE22,ლიბერთი,Liberty,Либерти,NaN,Q6541585,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
440,way,234902042,bank,yes,JSCRGE22,კრედო ბანკი,Credo Bank,Кредо Банк,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
441,way,1073296890,bank,yes,TCZBGE22,ზირაათ ბანკი,Ziraat Bank,Зираат Банк,Ziraat Bankası,Q696003,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
442,way,1201009491,bank,yes,TBCBGE22,თიბისი ბანკი,TBC Bank,ТиБиСи Банк,NaN,Q2620975,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# Filter the GeoDataFrame to include only nodes, aka points
nodes_gdf = new_gdf[new_gdf['geometry'].type == 'Point']
nodes_gdf

,element_type,osmid,amenity,atm,bic,brand,brand:en,brand:ru,brand:tr,brand:wikidata,...,payment:american_express,payment:apple_pay,payment:diners_club,payment:discover_card,payment:google_pay,payment:unionpay,access,membership,shop,description:en
0,node,5312262226,bank,yes,BAGAGE22,საქართველოს ბანკი,Bank of Georgia,Банк Грузии,Gürcistan Bankası,Q2469733,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,node,9679293599,bank,yes,JSCRGE22,კრედო ბანკი,Credo Bank,Кредо Банк,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,node,9991255389,bank,yes,TEBAGE22,ტერაბანკი,Terabank,Терабанк,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,node,10140092587,bank,yes,TBCBGE22,თიბისი ბანკი,TBC Bank,ТиБиСи Банк,NaN,Q2620975,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,node,10910789508,bank,yes,BAGAGE22,საქართველოს ბანკი,Bank of Georgia,Банк Грузии,Gürcistan Bankası,Q2469733,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,node,11534002912,bank,NaN,LBRTGE22,ლიბერთი,Liberty,Либерти,NaN,Q6541585,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
431,node,11534002913,bank,NaN,NaN,კრისტალი,Crystal,Кристал,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,money_lender,NaN
432,node,11534002972,bank,NaN,LBRTGE22,ლიბერთი,Liberty,Либерти,NaN,Q6541585,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
433,node,11595023298,bank,NaN,TBCBGE22,თიბისი ბანკი,TBC Bank,ТиБиСи Банк,NaN,Q2620975,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
434,node,11631035396,bank,yes,CBASGE22,ბაზისბანკი,Basisbank,БазисБанк,NaN,Q16365625,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
# Define the file path for saving the GeoPackage file
output_file = "/Users/giorgikankia/Documents/GitHub/urbanyxv1/data/pois-bank.geojson"

# Save the filtered GeoDataFrame to a GeoPackage file
nodes_gdf.to_file(output_file, driver='GeoJSON')