In [1]:
import osmnx as ox
import geopandas as gpd
import pandas as pd

In [2]:
place = ["Tbilisi, Georgia", 
         "Batumi, Georgia", 
         "Kutaisi, Georgia", 
         "Zugdidi, Georgia", 
         "Gori, Georgia", 
         "Poti, Georgia",
         "Sokhumi, Georgia",
         "Akhaltsikhe, Georgia"
        ]

In [27]:
tags = {"amenity": "payment_terminal"}
gdf = ox.features_from_place(place, tags)
gdf

                                   amenity  check_date      opening_hours  \
element_type osmid
node         10016644797  payment_terminal  2022-09-11               24/7
             10016644798  payment_terminal  2023-03-24               24/7
             10016644799  payment_terminal  2022-09-11               24/7
             10016644800  payment_terminal  2022-09-11               24/7
             10017876200  payment_terminal  2022-11-04               24/7
...                                    ...         ...                ...
             11406251576  payment_terminal  2023-12-14               24/7
             11521607032  payment_terminal         NaN  Mo-Fr 09:00-18:00
             11521607033  payment_terminal         NaN  Mo-Fr 09:00-18:00
             11731227186  payment_terminal  2024-03-14                NaN
             11731227188  payment_terminal  2024-03-14                NaN

                         payment:cash payment:coins  \
element_type osmid
node         10016644797          yes           yes
             10016644798          yes           yes
             10016644799          yes           yes
             10016644800          yes           yes
             10017876200          yes            no
...                               ...           ...
             11406251576          yes            no
             11521607032          yes            no
             11521607033          yes            no
             11731227186          NaN           NaN
             11731227188          NaN           NaN

                                           geometry covered indoor  \
element_type osmid
node         10016644797  POINT (41.60866 41.63435)     NaN    NaN
             10016644798  POINT (41.60836 41.63393)     yes     no
             10016644799  POINT (41.60857 41.63418)     NaN    NaN
             10016644800  POINT (41.60856 41.63415)     yes     no
             10017876200  POINT (41.61137 41.63531)     yes     no
...                                             ...     ...    ...
             11406251576  POINT (44.73096 41.72404)     NaN    NaN
             11521607032  POINT (44.80617 41.69914)     NaN    NaN
             11521607033  POINT (44.80647 41.69882)     NaN    NaN
             11731227186  POINT (44.79689 41.70221)     NaN    NaN
             11731227188  POINT (44.80959 41.68979)     NaN    NaN

                                      brand brand:wikidata  ... language:ka  \
element_type osmid                                          ...
node         10016644797                NaN            NaN  ...         NaN
             10016644798                NaN            NaN  ...         NaN
             10016644799                NaN            NaN  ...         NaN
             10016644800                NaN            NaN  ...         NaN
             10017876200  საქართველოს ბანკი       Q2469733  ...         NaN
...                                     ...            ...  ...         ...
             11406251576  საქართველოს ბანკი       Q2469733  ...         NaN
             11521607032  საქართველოს ბანკი       Q2469733  ...         NaN
             11521607033       თიბისი ბანკი       Q2620975  ...         NaN
             11731227186                NaN            NaN  ...         NaN
             11731227188                NaN            NaN  ...         NaN

                          lit                    contact:instagram  \
element_type osmid
node         10016644797  NaN                                  NaN
             10016644798  NaN                                  NaN
             10016644799  NaN                                  NaN
             10016644800  NaN                                  NaN
             10017876200  NaN                                  NaN
...                       ...                                  ...
             11406251576  NaN  https://instagram.com/bankofgeorgia
             11521607032  NaN  https://instagram.com/bankofgeorgia
             11521607033  NaN                                  NaN
             11731227186  NaN                                  NaN
             11731227188  NaN                                  NaN

                         addr:postcode payment:cards payment:credit_cards  \
element_type osmid
node         10016644797           NaN           NaN                  NaN
             10016644798           NaN           NaN                  NaN
             10016644799           NaN           NaN                  NaN
             10016644800           NaN           NaN                  NaN
             10017876200           NaN           NaN                  NaN
...                                ...           ...                  ...
             11406251576           NaN           NaN                  NaN
             11521607032           NaN           NaN                  NaN
             11521607033           NaN           NaN                  NaN
             11731227186           NaN           NaN                  NaN
             11731227188           NaN           NaN                  NaN

                         payment:debit_cards addr:street:en currency:crypto  \
element_type osmid
node         10016644797                 NaN            NaN             NaN
             10016644798                 NaN            NaN             NaN
             10016644799                 NaN            NaN             NaN
             10016644800                 NaN            NaN             NaN
             10017876200                 NaN            NaN             NaN
...                                      ...            ...             ...
             11406251576                 NaN            NaN             NaN
             11521607032                 NaN            NaN             NaN
             11521607033                 NaN            NaN             NaN
             11731227186                 NaN            NaN             NaN
             11731227188                 NaN            NaN             NaN

                         network
element_type osmid
node         10016644797     NaN
             10016644798     NaN
             10016644799     NaN
             10016644800     NaN
             10017876200     NaN
...                          ...
             11406251576     NaN
             11521607032     NaN
             11521607033     NaN
             11731227186     NaN
             11731227188     NaN

[1742 rows x 66 columns]

In [28]:
gdf.reset_index([0, 1])
new_gdf = gdf.reset_index(['element_type','osmid'])
new_gdf

,element_type,osmid,amenity,check_date,opening_hours,payment:cash,payment:coins,geometry,covered,indoor,...,language:ka,lit,contact:instagram,addr:postcode,payment:cards,payment:credit_cards,payment:debit_cards,addr:street:en,currency:crypto,network
0,node,10016644797,payment_terminal,2022-09-11,24/7,yes,yes,POINT (41.60866 41.63435),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,node,10016644798,payment_terminal,2023-03-24,24/7,yes,yes,POINT (41.60836 41.63393),yes,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,node,10016644799,payment_terminal,2022-09-11,24/7,yes,yes,POINT (41.60857 41.63418),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,node,10016644800,payment_terminal,2022-09-11,24/7,yes,yes,POINT (41.60856 41.63415),yes,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,node,10017876200,payment_terminal,2022-11-04,24/7,yes,no,POINT (41.61137 41.63531),yes,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1737,node,11406251576,payment_terminal,2023-12-14,24/7,yes,no,POINT (44.73096 41.72404),NaN,NaN,...,NaN,NaN,https://instagram.com/bankofgeorgia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1738,node,11521607032,payment_terminal,NaN,Mo-Fr 09:00-18:00,yes,no,POINT (44.80617 41.69914),NaN,NaN,...,NaN,NaN,https://instagram.com/bankofgeorgia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1739,node,11521607033,payment_terminal,NaN,Mo-Fr 09:00-18:00,yes,no,POINT (44.80647 41.69882),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1740,node,11731227186,payment_terminal,2024-03-14,NaN,NaN,NaN,POINT (44.79689 41.70221),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1741,node,11731227188,payment_terminal,2024-03-14,NaN,NaN,NaN,POINT (44.80959 41.68979),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
# Filter the GeoDataFrame to include only nodes, aka points
nodes_gdf = new_gdf[new_gdf['geometry'].type == 'Point']
nodes_gdf

,element_type,osmid,amenity,check_date,opening_hours,payment:cash,payment:coins,geometry,covered,indoor,...,language:ka,lit,contact:instagram,addr:postcode,payment:cards,payment:credit_cards,payment:debit_cards,addr:street:en,currency:crypto,network
0,node,10016644797,payment_terminal,2022-09-11,24/7,yes,yes,POINT (41.60866 41.63435),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,node,10016644798,payment_terminal,2023-03-24,24/7,yes,yes,POINT (41.60836 41.63393),yes,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,node,10016644799,payment_terminal,2022-09-11,24/7,yes,yes,POINT (41.60857 41.63418),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,node,10016644800,payment_terminal,2022-09-11,24/7,yes,yes,POINT (41.60856 41.63415),yes,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,node,10017876200,payment_terminal,2022-11-04,24/7,yes,no,POINT (41.61137 41.63531),yes,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1737,node,11406251576,payment_terminal,2023-12-14,24/7,yes,no,POINT (44.73096 41.72404),NaN,NaN,...,NaN,NaN,https://instagram.com/bankofgeorgia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1738,node,11521607032,payment_terminal,NaN,Mo-Fr 09:00-18:00,yes,no,POINT (44.80617 41.69914),NaN,NaN,...,NaN,NaN,https://instagram.com/bankofgeorgia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1739,node,11521607033,payment_terminal,NaN,Mo-Fr 09:00-18:00,yes,no,POINT (44.80647 41.69882),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1740,node,11731227186,payment_terminal,2024-03-14,NaN,NaN,NaN,POINT (44.79689 41.70221),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1741,node,11731227188,payment_terminal,2024-03-14,NaN,NaN,NaN,POINT (44.80959 41.68979),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
# Populating column1 with values from column2
nodes_gdf.loc[:, "amenity"] = nodes_gdf["brand:en"]
nodes_gdf

,element_type,osmid,amenity,check_date,opening_hours,payment:cash,payment:coins,geometry,covered,indoor,...,language:ka,lit,contact:instagram,addr:postcode,payment:cards,payment:credit_cards,payment:debit_cards,addr:street:en,currency:crypto,network
0,node,10016644797,NaN,2022-09-11,24/7,yes,yes,POINT (41.60866 41.63435),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,node,10016644798,NaN,2023-03-24,24/7,yes,yes,POINT (41.60836 41.63393),yes,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,node,10016644799,NaN,2022-09-11,24/7,yes,yes,POINT (41.60857 41.63418),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,node,10016644800,NaN,2022-09-11,24/7,yes,yes,POINT (41.60856 41.63415),yes,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,node,10017876200,NaN,2022-11-04,24/7,yes,no,POINT (41.61137 41.63531),yes,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1737,node,11406251576,Bank of Georgia,2023-12-14,24/7,yes,no,POINT (44.73096 41.72404),NaN,NaN,...,NaN,NaN,https://instagram.com/bankofgeorgia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1738,node,11521607032,Bank of Georgia,NaN,Mo-Fr 09:00-18:00,yes,no,POINT (44.80617 41.69914),NaN,NaN,...,NaN,NaN,https://instagram.com/bankofgeorgia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1739,node,11521607033,TBC Bank,NaN,Mo-Fr 09:00-18:00,yes,no,POINT (44.80647 41.69882),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1740,node,11731227186,NaN,2024-03-14,NaN,NaN,NaN,POINT (44.79689 41.70221),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1741,node,11731227188,NaN,2024-03-14,NaN,NaN,NaN,POINT (44.80959 41.68979),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
# Define the file path for saving the GeoPackage file
output_file = "/Users/giorgikankia/Documents/GitHub/urbanyxv1/data/pois-payment_terminal.geojson"

# Save the filtered GeoDataFrame to a GeoPackage file
nodes_gdf.to_file(output_file, driver='GeoJSON')